import { Button } from "@/components/ui/button";
import { Download, FileJson, FileText } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import jsPDF from "jspdf";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";

interface ExportOptionsProps {
  profile: any;
}

export const ExportOptions = ({ profile }: ExportOptionsProps) => {
  const { toast } = useToast();

  const exportAsJSON = () => {
    try {
      const jsonString = JSON.stringify(profile, null, 2);
      const blob = new Blob([jsonString], { type: "application/json" });
      const url = URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.href = url;
      link.download = `skill-profile-${Date.now()}.json`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);

      toast({
        title: "JSON Downloaded",
        description: "Your skill profile has been exported as JSON.",
      });
    } catch (error) {
      console.error("Export error:", error);
      toast({
        title: "Export Failed",
        description: "Failed to export JSON file.",
        variant: "destructive",
      });
    }
  };

  const exportAsPDF = () => {
    try {
      const doc = new jsPDF();
      let yPosition = 20;
      const pageHeight = doc.internal.pageSize.height;
      const margin = 20;
      const lineHeight = 7;

      // Helper function to add text with page break handling
      const addText = (text: string, fontSize = 12, isBold = false) => {
        if (yPosition > pageHeight - margin) {
          doc.addPage();
          yPosition = margin;
        }
        doc.setFontSize(fontSize);
        if (isBold) {
          doc.setFont("helvetica", "bold");
        } else {
          doc.setFont("helvetica", "normal");
        }
        
        // Split long text into multiple lines
        const splitText = doc.splitTextToSize(text, 170);
        doc.text(splitText, margin, yPosition);
        yPosition += lineHeight * splitText.length;
      };

      // Title
      addText("SkillSense - Skill Profile Analysis", 18, true);
      yPosition += 5;
      
      // Date
      addText(`Generated: ${new Date().toLocaleDateString()}`, 10);
      yPosition += 10;

      // Profile Summary
      if (profile.name) {
        addText(`Name: ${profile.name}`, 14, true);
      }
      if (profile.title) {
        addText(`Title: ${profile.title}`, 12);
      }
      if (profile.summary) {
        yPosition += 5;
        addText("Summary:", 12, true);
        addText(profile.summary, 11);
      }

      yPosition += 10;

      // Completeness Score
      if (profile.completeness) {
        addText(`Profile Completeness: ${profile.completeness}%`, 12, true);
        yPosition += 5;
      }

      // Top Skills
      if (profile.topSkills && profile.topSkills.length > 0) {
        yPosition += 5;
        addText("Top Skills:", 14, true);
        yPosition += 3;
        
        profile.topSkills.slice(0, 10).forEach((skill: any) => {
          addText(`• ${skill.name} (Confidence: ${skill.confidence}%)`, 11);
        });
      }

      // Categories
      if (profile.categories) {
        yPosition += 10;
        addText("Skill Categories:", 14, true);
        yPosition += 3;

        Object.entries(profile.categories).forEach(([category, skills]: [string, any]) => {
          if (Array.isArray(skills) && skills.length > 0) {
            const categoryTitle = category.replace(/_/g, " ").replace(/\b\w/g, l => l.toUpperCase());
            addText(`${categoryTitle}:`, 12, true);
            
            skills.forEach((skill: any) => {
              const evidence = skill.evidence && skill.evidence.length > 0 
                ? ` - ${skill.evidence[0].substring(0, 100)}...`
                : "";
              addText(`  • ${skill.name} (${skill.confidence}%, ${skill.type})${evidence}`, 10);
            });
            yPosition += 3;
          }
        });
      }

      // Data Sources
      if (profile.dataSources && profile.dataSources.length > 0) {
        yPosition += 10;
        addText("Data Sources:", 12, true);
        addText(profile.dataSources.join(", "), 11);
      }

      // Footer
      doc.setFontSize(8);
      doc.setTextColor(128);
      const footerText = "Generated by SkillSense - Unlock Your Hidden Potential";
      doc.text(footerText, margin, pageHeight - 10);

      // Save PDF
      doc.save(`skill-profile-${Date.now()}.pdf`);

      toast({
        title: "PDF Downloaded",
        description: "Your skill profile has been exported as PDF.",
      });
    } catch (error) {
      console.error("PDF export error:", error);
      toast({
        title: "Export Failed",
        description: "Failed to export PDF file.",
        variant: "destructive",
      });
    }
  };

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button variant="outline" className="gap-2">
          <Download className="w-4 h-4" />
          Export Profile
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end">
        <DropdownMenuItem onClick={exportAsJSON} className="gap-2 cursor-pointer">
          <FileJson className="w-4 h-4" />
          Download as JSON
        </DropdownMenuItem>
        <DropdownMenuItem onClick={exportAsPDF} className="gap-2 cursor-pointer">
          <FileText className="w-4 h-4" />
          Download as PDF
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  );
};
