import { Button } from "@/components/ui/button";
import { Download, FileJson, FileText } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import jsPDF from "jspdf";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";

interface ExportOptionsProps {
  profile: any;
}

export const ExportOptions = ({ profile }: ExportOptionsProps) => {
  const { toast } = useToast();

  const exportAsJSON = () => {
    try {
      const jsonString = JSON.stringify(profile, null, 2);
      const blob = new Blob([jsonString], { type: "application/json" });
      const url = URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.href = url;
      link.download = `skill-profile-${Date.now()}.json`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);

      toast({
        title: "JSON Downloaded",
        description: "Your skill profile has been exported as JSON.",
      });
    } catch (error) {
      console.error("Export error:", error);
      toast({
        title: "Export Failed",
        description: "Failed to export JSON file.",
        variant: "destructive",
      });
    }
  };

  const exportAsPDF = () => {
    try {
      const doc = new jsPDF();
      let yPosition = 20;
      const pageHeight = doc.internal.pageSize.height;
      const pageWidth = doc.internal.pageSize.width;
      const margin = 20;
      const lineHeight = 7;
      const primaryColor: [number, number, number] = [59, 130, 246]; // Blue
      const accentColor: [number, number, number] = [147, 197, 253]; // Light blue
      const mutedColor: [number, number, number] = [156, 163, 175]; // Gray

      // Helper function to check and add new page if needed
      const checkPageBreak = (neededSpace: number) => {
        if (yPosition + neededSpace > pageHeight - 30) {
          addFooter();
          doc.addPage();
          yPosition = margin;
        }
      };

      // Helper function to add footer
      const addFooter = () => {
        doc.setFontSize(8);
        doc.setTextColor(128, 128, 128);
        const footerText = "Generated by SkillSense - Unlock Your Hidden Potential";
        const textWidth = doc.getTextWidth(footerText);
        doc.text(footerText, (pageWidth - textWidth) / 2, pageHeight - 10);
      };

      // Helper function to draw progress bar
      const drawProgressBar = (x: number, y: number, width: number, percentage: number) => {
        // Background bar
        doc.setFillColor(240, 240, 240);
        doc.rect(x, y, width, 4, "F");
        
        // Progress bar
        doc.setFillColor(...primaryColor);
        doc.rect(x, y, (width * percentage) / 100, 4, "F");
      };

      // Helper function to draw section header
      const drawSectionHeader = (title: string) => {
        checkPageBreak(15);
        doc.setFillColor(...primaryColor);
        doc.rect(margin, yPosition, pageWidth - 2 * margin, 8, "F");
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(12);
        doc.setFont("helvetica", "bold");
        doc.text(title, margin + 3, yPosition + 6);
        doc.setTextColor(0, 0, 0);
        yPosition += 13;
      };

      // ===== PAGE HEADER =====
      doc.setFillColor(...primaryColor);
      doc.rect(0, 0, pageWidth, 35, "F");
      
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(20);
      doc.setFont("helvetica", "bold");
      doc.text("SkillSense - Skill Profile Analysis", margin, 15);
      
      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      doc.text(`Generated: ${new Date().toLocaleDateString()}`, margin, 25);
      
      if (profile.name) {
        const nameText = `Name: ${profile.name}`;
        const nameWidth = doc.getTextWidth(nameText);
        doc.text(nameText, pageWidth - margin - nameWidth, 25);
      }

      doc.setTextColor(0, 0, 0);
      yPosition = 45;

      // ===== SUMMARY SECTION =====
      if (profile.summary) {
        drawSectionHeader("Summary");
        doc.setFontSize(10);
        doc.setFont("helvetica", "normal");
        const summaryLines = doc.splitTextToSize(profile.summary, pageWidth - 2 * margin - 10);
        summaryLines.forEach((line: string) => {
          checkPageBreak(7);
          doc.text(line, margin + 5, yPosition);
          yPosition += 6;
        });
        yPosition += 8;
      }

      // ===== KEY METRICS SECTION (TWO COLUMNS) =====
      drawSectionHeader("Profile Overview");
      
      const columnWidth = (pageWidth - 2 * margin - 10) / 2;
      
      // Left Column - Profile Completeness
      doc.setFillColor(250, 250, 250);
      doc.rect(margin, yPosition, columnWidth, 25, "F");
      doc.setDrawColor(...mutedColor);
      doc.rect(margin, yPosition, columnWidth, 25, "S");
      
      doc.setFontSize(10);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...mutedColor);
      doc.text("Profile Completeness", margin + 5, yPosition + 8);
      
      doc.setFontSize(18);
      doc.setTextColor(...primaryColor);
      const completeness = profile.completeness || 0;
      doc.text(`${completeness}%`, margin + 5, yPosition + 20);
      
      // Right Column - Total Skills
      const totalSkills = Object.values(profile.categories || {})
        .flat()
        .filter((skill: any) => skill && skill.name).length;
      
      doc.setFillColor(250, 250, 250);
      doc.rect(margin + columnWidth + 10, yPosition, columnWidth, 25, "F");
      doc.setDrawColor(...mutedColor);
      doc.rect(margin + columnWidth + 10, yPosition, columnWidth, 25, "S");
      
      doc.setFontSize(10);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...mutedColor);
      doc.text("Total Skills Identified", margin + columnWidth + 15, yPosition + 8);
      
      doc.setFontSize(18);
      doc.setTextColor(...primaryColor);
      doc.text(`${totalSkills}`, margin + columnWidth + 15, yPosition + 20);
      
      yPosition += 35;

      // ===== TOP SKILLS SECTION =====
      if (profile.topSkills && profile.topSkills.length > 0) {
        drawSectionHeader("Top Skills");
        
        profile.topSkills.slice(0, 10).forEach((skill: any) => {
          checkPageBreak(10);
          doc.setFontSize(10);
          doc.setFont("helvetica", "normal");
          doc.text(`• ${skill.name}`, margin + 5, yPosition);
          
          const confidenceText = `${skill.confidence}%`;
          const confidenceX = pageWidth - margin - 40;
          doc.setTextColor(...primaryColor);
          doc.setFont("helvetica", "bold");
          doc.text(confidenceText, confidenceX, yPosition);
          doc.setTextColor(0, 0, 0);
          
          yPosition += 7;
        });
        yPosition += 8;
      }

      // ===== SKILL CATEGORIES SECTION (TWO-COLUMN WITH MINI-CARDS) =====
      if (profile.categories) {
        Object.entries(profile.categories).forEach(([category, skills]: [string, any]) => {
          if (Array.isArray(skills) && skills.length > 0) {
            const categoryTitle = category.replace(/_/g, " ").replace(/\b\w/g, l => l.toUpperCase());
            drawSectionHeader(categoryTitle);
            
            // Two-column layout
            let columnIndex = 0;
            const skillColumnWidth = (pageWidth - 2 * margin - 10) / 2;
            
            skills.forEach((skill: any, index: number) => {
              const cardHeight = 22;
              checkPageBreak(cardHeight + 5);
              
              const xPos = columnIndex === 0 
                ? margin 
                : margin + skillColumnWidth + 10;
              
              // Draw mini-card background
              doc.setFillColor(248, 250, 252);
              doc.rect(xPos, yPosition, skillColumnWidth, cardHeight, "F");
              doc.setDrawColor(...accentColor);
              doc.rect(xPos, yPosition, skillColumnWidth, cardHeight, "S");
              
              // Skill name (bold)
              doc.setFontSize(10);
              doc.setFont("helvetica", "bold");
              doc.setTextColor(0, 0, 0);
              const skillNameLines = doc.splitTextToSize(skill.name, skillColumnWidth - 10);
              doc.text(skillNameLines[0], xPos + 5, yPosition + 6);
              
              // Confidence score and progress bar
              doc.setFontSize(8);
              doc.setFont("helvetica", "bold");
              doc.setTextColor(...primaryColor);
              doc.text(`${skill.confidence}%`, xPos + 5, yPosition + 13);
              
              // Progress bar
              drawProgressBar(xPos + 25, yPosition + 10, skillColumnWidth - 30, skill.confidence);
              
              // Skill type badge
              doc.setFontSize(7);
              doc.setFont("helvetica", "normal");
              doc.setTextColor(...mutedColor);
              const typeText = skill.type || "implicit";
              doc.text(typeText.toUpperCase(), xPos + 5, yPosition + 19);
              
              // Evidence source (cleaned)
              if (skill.evidence && skill.evidence.length > 0) {
                const evidenceSource = skill.evidence[0].startsWith("From") 
                  ? skill.evidence[0].substring(0, 30)
                  : `Evidence: From ${profile.dataSources?.[0] || "CV"}`;
                doc.setFontSize(7);
                doc.setTextColor(...mutedColor);
                const evidenceLines = doc.splitTextToSize(evidenceSource, skillColumnWidth - 10);
                doc.text(evidenceLines[0], xPos + skillColumnWidth - 5 - doc.getTextWidth(evidenceLines[0]), yPosition + 19);
              }
              
              // Move to next position
              columnIndex++;
              if (columnIndex > 1) {
                columnIndex = 0;
                yPosition += cardHeight + 3;
              }
            });
            
            // If odd number of skills, move y position for next section
            if (skills.length % 2 !== 0) {
              yPosition += 25;
            }
            yPosition += 8;
          }
        });
      }

      // ===== DATA SOURCES SECTION =====
      if (profile.dataSources && profile.dataSources.length > 0) {
        checkPageBreak(20);
        drawSectionHeader("Data Sources");
        doc.setFontSize(10);
        doc.setFont("helvetica", "normal");
        const sources = profile.dataSources.map((s: string) => s.toUpperCase()).join(", ");
        doc.text(sources, margin + 5, yPosition);
        yPosition += 10;
      }

      // Add footer to last page
      addFooter();

      // Save PDF
      doc.save(`skillsense-profile-${Date.now()}.pdf`);

      toast({
        title: "PDF Downloaded",
        description: "Your professional skill profile has been exported as PDF.",
      });
    } catch (error) {
      console.error("PDF export error:", error);
      toast({
        title: "Export Failed",
        description: "Failed to export PDF file.",
        variant: "destructive",
      });
    }
  };

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button variant="outline" className="gap-2">
          <Download className="w-4 h-4" />
          Export Profile
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end">
        <DropdownMenuItem onClick={exportAsJSON} className="gap-2 cursor-pointer">
          <FileJson className="w-4 h-4" />
          Download as JSON
        </DropdownMenuItem>
        <DropdownMenuItem onClick={exportAsPDF} className="gap-2 cursor-pointer">
          <FileText className="w-4 h-4" />
          Download as PDF
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  );
};
